site_name: Fiori Role Testing
site_url: https://fioriroletesting.com/

nav:
  - Installation: installation.md
  - Get an offer: offer.md
  - Get it for free: free-offer.md

copyright: Copyright &copy; 2024 Nype

theme:
  name: nype
  custom_dir: overrides
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  nype_config:
    contact_form_action_hex: 6148523063484d364c79396d62334a74637935316269317a6447463061574d75593239744c325a76636d317a4c7a63304f546b314d445930597a63304f44566d4e6a55324e4755354d6a45304e6d5a6d596a6c6c5a574934596a63344e7a42695954553d
    contact_form_email_hex: 5047456761484a6c5a6a306962574670624852764f6d5a6864554275634755755932302f63335669616d566a6444314761573979615342536232786c4946526c63335270626d6336494334754c69492b5a6d4631514735775a53356a625477765954343d

# Explicitly confirm there is awareness of files not in nav
not_in_nav: |
  /index.md
  /contact.md
  /contact-success.md
  /get-for-free.md
  /installation/*

# Together with --strict flag it allows to crash CI if an error occurs and prevent shipping broken sites
validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn  # If needed change to 'relative_to_docs'
  links:
    not_found: warn
    anchors: warn
    absolute_links: warn  # If needed change to 'relative_to_docs'
    unrecognized_links: warn

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/extra.js




extra:
  analytics:
    provider: google
    property: G-3VJR286HQC
  social:
    - icon: ext/nype-logo
      link: https://npe.cm/?ref=fioriroletesting
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/company/fiori-tracker/
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/fioritracker
    - icon: fontawesome/brands/discord
      link: https://discord.gg/xGNzmej4KE

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - md_in_html

plugins:
  - search
  - social:
      enabled: !ENV [CI, false]
      cards_layout_options:
        background_color: "#0d0d72"  # same color as the corner in the logo.png
  - minify:
      enabled: !ENV [CI, false]
      minify_html: true
      minify_js: false
      minify_css: false
      htmlmin_opts:
          remove_comments: true
      cache_safe: true
  - sap_icons
  - macros:
      on_error_fail: !ENV [CI, false]

